/**
 * 本地开发种子数据脚本（可重复执行）
 * 用法: npx tsx scripts/seed-dev.ts
 * 生成 3 源模拟数据 + 碎片主题，用于本地测试大扫除/聚合
 */
import dotenv from 'dotenv'
import path from 'path'
dotenv.config({ path: path.resolve(process.cwd(), '.env.local') })
import { Pool } from 'pg'

const pool = new Pool({ connectionString: process.env.DATABASE_URL })
async function main() {
  const now = Date.now()

  // GitHub 仓库（含重复主题倾向的数据）
  const github = [
    ['github:gh1', 'github', 'game trainer 1', 'https://github.com/o1/r1', 'game'],
    ['github:gh2', 'github', 'crypto bot 2', 'https://github.com/o2/r2', 'crypto'],
    ['github:gh3', 'github', 'react lib 3', 'https://github.com/o3/r3', 'web'],
    ['github:gh4', 'github', 'CLI tool 4', 'https://github.com/o4/r4', 'devtools'],
    ['github:gh5', 'github', 'scanner 5', 'https://github.com/o5/r5', 'security'],
    ['github:gh6', 'github', 'dataset 6', 'https://github.com/o6/r6', 'data'],
    ['github:gh7', 'github', 'figma plugin 7', 'https://github.com/o7/r7', 'design'],
    ['github:gh8', 'github', 'AI tool 8', 'https://github.com/o8/r8', 'ai'],
    ['github:gh9', 'github', 'game trainer 9', 'https://github.com/o9/r9', 'game'],
    ['github:gh10', 'github', 'crypto bot 10', 'https://github.com/o10/r10', 'crypto'],
    ['github:gh11', 'github', 'react lib 11', 'https://github.com/o11/r11', 'web'],
    ['github:gh12', 'github', 'CLI tool 12', 'https://github.com/o12/r12', 'devtools'],
    ['github:gh13', 'github', 'scanner 13', 'https://github.com/o13/r13', 'security'],
    ['github:gh14', 'github', 'dataset 14', 'https://github.com/o14/r14', 'data'],
    ['github:gh15', 'github', 'figma plugin 15', 'https://github.com/o15/r15', 'design'],
    ['github:gh16', 'github', 'AI tool 16', 'https://github.com/o16/r16', 'ai'],
    ['github:gh17', 'github', 'game trainer 17', 'https://github.com/o17/r17', 'game'],
    ['github:gh18', 'github', 'crypto bot 18', 'https://github.com/o18/r18', 'crypto'],
    ['github:gh19', 'github', 'react lib 19', 'https://github.com/o19/r19', 'web'],
    ['github:gh20', 'github', 'CLI tool 20', 'https://github.com/o20/r20', 'devtools'],
    ['github:gh21', 'github', 'scanner 21', 'https://github.com/o21/r21', 'security'],
    ['github:gh22', 'github', 'dataset 22', 'https://github.com/o22/r22', 'data'],
    ['github:gh23', 'github', 'figma plugin 23', 'https://github.com/o23/r23', 'design'],
    ['github:gh24', 'github', 'AI tool 24', 'https://github.com/o24/r24', 'ai'],
    ['github:gh25', 'github', 'game trainer 25', 'https://github.com/o25/r25', 'game'],
    ['github:gh26', 'github', 'crypto bot 26', 'https://github.com/o26/r26', 'crypto'],
    ['github:gh27', 'github', 'react lib 27', 'https://github.com/o27/r27', 'web'],
    ['github:gh28', 'github', 'CLI tool 28', 'https://github.com/o28/r28', 'devtools'],
    ['github:gh29', 'github', 'scanner 29', 'https://github.com/o29/r29', 'security'],
    ['github:gh30', 'github', 'dataset 30', 'https://github.com/o30/r30', 'data'],
    ['github:gh31', 'github', 'figma plugin 31', 'https://github.com/o31/r31', 'design'],
    ['github:gh32', 'github', 'AI tool 32', 'https://github.com/o32/r32', 'ai'],
    ['github:gh33', 'github', 'game trainer 33', 'https://github.com/o33/r33', 'game'],
    ['github:gh34', 'github', 'crypto bot 34', 'https://github.com/o34/r34', 'crypto'],
    ['github:gh35', 'github', 'react lib 35', 'https://github.com/o35/r35', 'web'],
    ['github:gh36', 'github', 'CLI tool 36', 'https://github.com/o36/r36', 'devtools'],
    ['github:gh37', 'github', 'scanner 37', 'https://github.com/o37/r37', 'security'],
    ['github:gh38', 'github', 'dataset 38', 'https://github.com/o38/r38', 'data'],
    ['github:gh39', 'github', 'figma plugin 39', 'https://github.com/o39/r39', 'design'],
    ['github:gh40', 'github', 'AI tool 40', 'https://github.com/o40/r40', 'ai'],
    ['github:gh41', 'github', 'game trainer 41', 'https://github.com/o41/r41', 'game'],
    ['github:gh42', 'github', 'crypto bot 42', 'https://github.com/o42/r42', 'crypto'],
    ['github:gh43', 'github', 'react lib 43', 'https://github.com/o43/r43', 'web'],
    ['github:gh44', 'github', 'CLI tool 44', 'https://github.com/o44/r44', 'devtools'],
    ['github:gh45', 'github', 'scanner 45', 'https://github.com/o45/r45', 'security'],
    ['github:gh46', 'github', 'dataset 46', 'https://github.com/o46/r46', 'data'],
    ['github:gh47', 'github', 'figma plugin 47', 'https://github.com/o47/r47', 'design'],
    ['github:gh48', 'github', 'AI tool 48', 'https://github.com/o48/r48', 'ai'],
    ['github:gh49', 'github', 'game trainer 49', 'https://github.com/o49/r49', 'game'],
    ['github:gh50', 'github', 'crypto bot 50', 'https://github.com/o50/r50', 'crypto'],
    ['github:gh51', 'github', 'react lib 51', 'https://github.com/o51/r51', 'web'],
    ['github:gh52', 'github', 'CLI tool 52', 'https://github.com/o52/r52', 'devtools'],
    ['github:gh53', 'github', 'scanner 53', 'https://github.com/o53/r53', 'security'],
    ['github:gh54', 'github', 'dataset 54', 'https://github.com/o54/r54', 'data'],
    ['github:gh55', 'github', 'figma plugin 55', 'https://github.com/o55/r55', 'design'],
    ['github:gh56', 'github', 'AI tool 56', 'https://github.com/o56/r56', 'ai'],
    ['github:gh57', 'github', 'game trainer 57', 'https://github.com/o57/r57', 'game'],
    ['github:gh58', 'github', 'crypto bot 58', 'https://github.com/o58/r58', 'crypto'],
    ['github:gh59', 'github', 'react lib 59', 'https://github.com/o59/r59', 'web'],
    ['github:gh60', 'github', 'CLI tool 60', 'https://github.com/o60/r60', 'devtools'],
    ['github:gh61', 'github', 'scanner 61', 'https://github.com/o61/r61', 'security'],
    ['github:gh62', 'github', 'dataset 62', 'https://github.com/o62/r62', 'data'],
    ['github:gh63', 'github', 'figma plugin 63', 'https://github.com/o63/r63', 'design'],
    ['github:gh64', 'github', 'AI tool 64', 'https://github.com/o64/r64', 'ai'],
    ['github:gh65', 'github', 'game trainer 65', 'https://github.com/o65/r65', 'game'],
    ['github:gh66', 'github', 'crypto bot 66', 'https://github.com/o66/r66', 'crypto'],
    ['github:gh67', 'github', 'react lib 67', 'https://github.com/o67/r67', 'web'],
    ['github:gh68', 'github', 'CLI tool 68', 'https://github.com/o68/r68', 'devtools'],
    ['github:gh69', 'github', 'scanner 69', 'https://github.com/o69/r69', 'security'],
    ['github:gh70', 'github', 'dataset 70', 'https://github.com/o70/r70', 'data'],
    ['github:gh71', 'github', 'figma plugin 71', 'https://github.com/o71/r71', 'design'],
    ['github:gh72', 'github', 'AI tool 72', 'https://github.com/o72/r72', 'ai'],
    ['github:gh73', 'github', 'game trainer 73', 'https://github.com/o73/r73', 'game'],
    ['github:gh74', 'github', 'crypto bot 74', 'https://github.com/o74/r74', 'crypto'],
    ['github:gh75', 'github', 'react lib 75', 'https://github.com/o75/r75', 'web'],
    ['github:gh76', 'github', 'CLI tool 76', 'https://github.com/o76/r76', 'devtools'],
    ['github:gh77', 'github', 'scanner 77', 'https://github.com/o77/r77', 'security'],
    ['github:gh78', 'github', 'dataset 78', 'https://github.com/o78/r78', 'data'],
    ['github:gh79', 'github', 'figma plugin 79', 'https://github.com/o79/r79', 'design'],
    ['github:gh80', 'github', 'AI tool 80', 'https://github.com/o80/r80', 'ai'],
    ['github:gh81', 'github', 'game trainer 81', 'https://github.com/o81/r81', 'game'],
    ['github:gh82', 'github', 'crypto bot 82', 'https://github.com/o82/r82', 'crypto'],
    ['github:gh83', 'github', 'react lib 83', 'https://github.com/o83/r83', 'web'],
    ['github:gh84', 'github', 'CLI tool 84', 'https://github.com/o84/r84', 'devtools'],
    ['github:gh85', 'github', 'scanner 85', 'https://github.com/o85/r85', 'security'],
    ['github:gh86', 'github', 'dataset 86', 'https://github.com/o86/r86', 'data'],
    ['github:gh87', 'github', 'figma plugin 87', 'https://github.com/o87/r87', 'design'],
    ['github:gh88', 'github', 'AI tool 88', 'https://github.com/o88/r88', 'ai'],
    ['github:gh89', 'github', 'game trainer 89', 'https://github.com/o89/r89', 'game'],
    ['github:gh90', 'github', 'crypto bot 90', 'https://github.com/o90/r90', 'crypto'],
    ['github:gh91', 'github', 'react lib 91', 'https://github.com/o91/r91', 'web'],
    ['github:gh92', 'github', 'CLI tool 92', 'https://github.com/o92/r92', 'devtools'],
    ['github:gh93', 'github', 'scanner 93', 'https://github.com/o93/r93', 'security'],
    ['github:gh94', 'github', 'dataset 94', 'https://github.com/o94/r94', 'data'],
    ['github:gh95', 'github', 'figma plugin 95', 'https://github.com/o95/r95', 'design'],
    ['github:gh96', 'github', 'AI tool 96', 'https://github.com/o96/r96', 'ai'],
    ['github:gh97', 'github', 'game trainer 97', 'https://github.com/o97/r97', 'game'],
    ['github:gh98', 'github', 'crypto bot 98', 'https://github.com/o98/r98', 'crypto'],
    ['github:gh99', 'github', 'react lib 99', 'https://github.com/o99/r99', 'web'],
    ['github:gh100', 'github', 'CLI tool 100', 'https://github.com/o100/r100', 'devtools'],
    ['github:gh101', 'github', 'scanner 101', 'https://github.com/o101/r101', 'security'],
    ['github:gh102', 'github', 'dataset 102', 'https://github.com/o102/r102', 'data'],
    ['github:gh103', 'github', 'figma plugin 103', 'https://github.com/o103/r103', 'design'],
    ['github:gh104', 'github', 'AI tool 104', 'https://github.com/o104/r104', 'ai'],
    ['github:gh105', 'github', 'game trainer 105', 'https://github.com/o105/r105', 'game'],
    ['github:gh106', 'github', 'crypto bot 106', 'https://github.com/o106/r106', 'crypto'],
    ['github:gh107', 'github', 'react lib 107', 'https://github.com/o107/r107', 'web'],
    ['github:gh108', 'github', 'CLI tool 108', 'https://github.com/o108/r108', 'devtools'],
    ['github:gh109', 'github', 'scanner 109', 'https://github.com/o109/r109', 'security'],
    ['github:gh110', 'github', 'dataset 110', 'https://github.com/o110/r110', 'data'],
    ['github:gh111', 'github', 'figma plugin 111', 'https://github.com/o111/r111', 'design'],
    ['github:gh112', 'github', 'AI tool 112', 'https://github.com/o112/r112', 'ai'],
    ['github:gh113', 'github', 'game trainer 113', 'https://github.com/o113/r113', 'game'],
    ['github:gh114', 'github', 'crypto bot 114', 'https://github.com/o114/r114', 'crypto'],
    ['github:gh115', 'github', 'react lib 115', 'https://github.com/o115/r115', 'web'],
    ['github:gh116', 'github', 'CLI tool 116', 'https://github.com/o116/r116', 'devtools'],
    ['github:gh117', 'github', 'scanner 117', 'https://github.com/o117/r117', 'security'],
    ['github:gh118', 'github', 'dataset 118', 'https://github.com/o118/r118', 'data'],
    ['github:gh119', 'github', 'figma plugin 119', 'https://github.com/o119/r119', 'design'],
    ['github:gh120', 'github', 'AI tool 120', 'https://github.com/o120/r120', 'ai'],
    ['github:gh121', 'github', 'game trainer 121', 'https://github.com/o121/r121', 'game'],
    ['github:gh122', 'github', 'crypto bot 122', 'https://github.com/o122/r122', 'crypto'],
    ['github:gh123', 'github', 'react lib 123', 'https://github.com/o123/r123', 'web'],
    ['github:gh124', 'github', 'CLI tool 124', 'https://github.com/o124/r124', 'devtools'],
    ['github:gh125', 'github', 'scanner 125', 'https://github.com/o125/r125', 'security'],
    ['github:gh126', 'github', 'dataset 126', 'https://github.com/o126/r126', 'data'],
    ['github:gh127', 'github', 'figma plugin 127', 'https://github.com/o127/r127', 'design'],
    ['github:gh128', 'github', 'AI tool 128', 'https://github.com/o128/r128', 'ai'],
    ['github:gh129', 'github', 'game trainer 129', 'https://github.com/o129/r129', 'game'],
    ['github:gh130', 'github', 'crypto bot 130', 'https://github.com/o130/r130', 'crypto'],
    ['github:gh131', 'github', 'react lib 131', 'https://github.com/o131/r131', 'web'],
    ['github:gh132', 'github', 'CLI tool 132', 'https://github.com/o132/r132', 'devtools'],
    ['github:gh133', 'github', 'scanner 133', 'https://github.com/o133/r133', 'security'],
    ['github:gh134', 'github', 'dataset 134', 'https://github.com/o134/r134', 'data'],
    ['github:gh135', 'github', 'figma plugin 135', 'https://github.com/o135/r135', 'design'],
    ['github:gh136', 'github', 'AI tool 136', 'https://github.com/o136/r136', 'ai'],
    ['github:gh137', 'github', 'game trainer 137', 'https://github.com/o137/r137', 'game'],
    ['github:gh138', 'github', 'crypto bot 138', 'https://github.com/o138/r138', 'crypto'],
    ['github:gh139', 'github', 'react lib 139', 'https://github.com/o139/r139', 'web'],
    ['github:gh140', 'github', 'CLI tool 140', 'https://github.com/o140/r140', 'devtools'],
    ['github:gh141', 'github', 'scanner 141', 'https://github.com/o141/r141', 'security'],
    ['github:gh142', 'github', 'dataset 142', 'https://github.com/o142/r142', 'data'],
    ['github:gh143', 'github', 'figma plugin 143', 'https://github.com/o143/r143', 'design'],
    ['github:gh144', 'github', 'AI tool 144', 'https://github.com/o144/r144', 'ai'],
    ['github:gh145', 'github', 'game trainer 145', 'https://github.com/o145/r145', 'game'],
    ['github:gh146', 'github', 'crypto bot 146', 'https://github.com/o146/r146', 'crypto'],
    ['github:gh147', 'github', 'react lib 147', 'https://github.com/o147/r147', 'web'],
    ['github:gh148', 'github', 'CLI tool 148', 'https://github.com/o148/r148', 'devtools'],
    ['github:gh149', 'github', 'scanner 149', 'https://github.com/o149/r149', 'security'],
    ['github:gh150', 'github', 'dataset 150', 'https://github.com/o150/r150', 'data'],
  ]
  // Product Hunt 产品
  const ph = [
    ['ph:1', 'ph', 'design tool 1', 'https://producthunt.com/p/1', 'design'],
    ['ph:2', 'ph', 'productivity 2', 'https://producthunt.com/p/2', 'prod'],
    ['ph:3', 'ph', 'SaaS 3', 'https://producthunt.com/p/3', 'saas'],
    ['ph:4', 'ph', 'mobile app 4', 'https://producthunt.com/p/4', 'mobile'],
    ['ph:5', 'ph', 'AI app 5', 'https://producthunt.com/p/5', 'ai'],
    ['ph:6', 'ph', 'design tool 6', 'https://producthunt.com/p/6', 'design'],
    ['ph:7', 'ph', 'productivity 7', 'https://producthunt.com/p/7', 'prod'],
    ['ph:8', 'ph', 'SaaS 8', 'https://producthunt.com/p/8', 'saas'],
    ['ph:9', 'ph', 'mobile app 9', 'https://producthunt.com/p/9', 'mobile'],
    ['ph:10', 'ph', 'AI app 10', 'https://producthunt.com/p/10', 'ai'],
    ['ph:11', 'ph', 'design tool 11', 'https://producthunt.com/p/11', 'design'],
    ['ph:12', 'ph', 'productivity 12', 'https://producthunt.com/p/12', 'prod'],
    ['ph:13', 'ph', 'SaaS 13', 'https://producthunt.com/p/13', 'saas'],
    ['ph:14', 'ph', 'mobile app 14', 'https://producthunt.com/p/14', 'mobile'],
    ['ph:15', 'ph', 'AI app 15', 'https://producthunt.com/p/15', 'ai'],
    ['ph:16', 'ph', 'design tool 16', 'https://producthunt.com/p/16', 'design'],
    ['ph:17', 'ph', 'productivity 17', 'https://producthunt.com/p/17', 'prod'],
    ['ph:18', 'ph', 'SaaS 18', 'https://producthunt.com/p/18', 'saas'],
    ['ph:19', 'ph', 'mobile app 19', 'https://producthunt.com/p/19', 'mobile'],
    ['ph:20', 'ph', 'AI app 20', 'https://producthunt.com/p/20', 'ai'],
    ['ph:21', 'ph', 'design tool 21', 'https://producthunt.com/p/21', 'design'],
    ['ph:22', 'ph', 'productivity 22', 'https://producthunt.com/p/22', 'prod'],
    ['ph:23', 'ph', 'SaaS 23', 'https://producthunt.com/p/23', 'saas'],
    ['ph:24', 'ph', 'mobile app 24', 'https://producthunt.com/p/24', 'mobile'],
    ['ph:25', 'ph', 'AI app 25', 'https://producthunt.com/p/25', 'ai'],
    ['ph:26', 'ph', 'design tool 26', 'https://producthunt.com/p/26', 'design'],
    ['ph:27', 'ph', 'productivity 27', 'https://producthunt.com/p/27', 'prod'],
    ['ph:28', 'ph', 'SaaS 28', 'https://producthunt.com/p/28', 'saas'],
    ['ph:29', 'ph', 'mobile app 29', 'https://producthunt.com/p/29', 'mobile'],
    ['ph:30', 'ph', 'AI app 30', 'https://producthunt.com/p/30', 'ai'],
    ['ph:31', 'ph', 'design tool 31', 'https://producthunt.com/p/31', 'design'],
    ['ph:32', 'ph', 'productivity 32', 'https://producthunt.com/p/32', 'prod'],
    ['ph:33', 'ph', 'SaaS 33', 'https://producthunt.com/p/33', 'saas'],
    ['ph:34', 'ph', 'mobile app 34', 'https://producthunt.com/p/34', 'mobile'],
    ['ph:35', 'ph', 'AI app 35', 'https://producthunt.com/p/35', 'ai'],
    ['ph:36', 'ph', 'design tool 36', 'https://producthunt.com/p/36', 'design'],
    ['ph:37', 'ph', 'productivity 37', 'https://producthunt.com/p/37', 'prod'],
    ['ph:38', 'ph', 'SaaS 38', 'https://producthunt.com/p/38', 'saas'],
    ['ph:39', 'ph', 'mobile app 39', 'https://producthunt.com/p/39', 'mobile'],
    ['ph:40', 'ph', 'AI app 40', 'https://producthunt.com/p/40', 'ai'],
    ['ph:41', 'ph', 'design tool 41', 'https://producthunt.com/p/41', 'design'],
    ['ph:42', 'ph', 'productivity 42', 'https://producthunt.com/p/42', 'prod'],
    ['ph:43', 'ph', 'SaaS 43', 'https://producthunt.com/p/43', 'saas'],
    ['ph:44', 'ph', 'mobile app 44', 'https://producthunt.com/p/44', 'mobile'],
    ['ph:45', 'ph', 'AI app 45', 'https://producthunt.com/p/45', 'ai'],
    ['ph:46', 'ph', 'design tool 46', 'https://producthunt.com/p/46', 'design'],
    ['ph:47', 'ph', 'productivity 47', 'https://producthunt.com/p/47', 'prod'],
    ['ph:48', 'ph', 'SaaS 48', 'https://producthunt.com/p/48', 'saas'],
    ['ph:49', 'ph', 'mobile app 49', 'https://producthunt.com/p/49', 'mobile'],
    ['ph:50', 'ph', 'AI app 50', 'https://producthunt.com/p/50', 'ai'],
    ['ph:51', 'ph', 'design tool 51', 'https://producthunt.com/p/51', 'design'],
    ['ph:52', 'ph', 'productivity 52', 'https://producthunt.com/p/52', 'prod'],
    ['ph:53', 'ph', 'SaaS 53', 'https://producthunt.com/p/53', 'saas'],
    ['ph:54', 'ph', 'mobile app 54', 'https://producthunt.com/p/54', 'mobile'],
    ['ph:55', 'ph', 'AI app 55', 'https://producthunt.com/p/55', 'ai'],
    ['ph:56', 'ph', 'design tool 56', 'https://producthunt.com/p/56', 'design'],
    ['ph:57', 'ph', 'productivity 57', 'https://producthunt.com/p/57', 'prod'],
    ['ph:58', 'ph', 'SaaS 58', 'https://producthunt.com/p/58', 'saas'],
    ['ph:59', 'ph', 'mobile app 59', 'https://producthunt.com/p/59', 'mobile'],
    ['ph:60', 'ph', 'AI app 60', 'https://producthunt.com/p/60', 'ai'],
    ['ph:61', 'ph', 'design tool 61', 'https://producthunt.com/p/61', 'design'],
    ['ph:62', 'ph', 'productivity 62', 'https://producthunt.com/p/62', 'prod'],
    ['ph:63', 'ph', 'SaaS 63', 'https://producthunt.com/p/63', 'saas'],
    ['ph:64', 'ph', 'mobile app 64', 'https://producthunt.com/p/64', 'mobile'],
    ['ph:65', 'ph', 'AI app 65', 'https://producthunt.com/p/65', 'ai'],
    ['ph:66', 'ph', 'design tool 66', 'https://producthunt.com/p/66', 'design'],
    ['ph:67', 'ph', 'productivity 67', 'https://producthunt.com/p/67', 'prod'],
    ['ph:68', 'ph', 'SaaS 68', 'https://producthunt.com/p/68', 'saas'],
    ['ph:69', 'ph', 'mobile app 69', 'https://producthunt.com/p/69', 'mobile'],
    ['ph:70', 'ph', 'AI app 70', 'https://producthunt.com/p/70', 'ai'],
    ['ph:71', 'ph', 'design tool 71', 'https://producthunt.com/p/71', 'design'],
    ['ph:72', 'ph', 'productivity 72', 'https://producthunt.com/p/72', 'prod'],
    ['ph:73', 'ph', 'SaaS 73', 'https://producthunt.com/p/73', 'saas'],
    ['ph:74', 'ph', 'mobile app 74', 'https://producthunt.com/p/74', 'mobile'],
    ['ph:75', 'ph', 'AI app 75', 'https://producthunt.com/p/75', 'ai'],
    ['ph:76', 'ph', 'design tool 76', 'https://producthunt.com/p/76', 'design'],
    ['ph:77', 'ph', 'productivity 77', 'https://producthunt.com/p/77', 'prod'],
    ['ph:78', 'ph', 'SaaS 78', 'https://producthunt.com/p/78', 'saas'],
    ['ph:79', 'ph', 'mobile app 79', 'https://producthunt.com/p/79', 'mobile'],
    ['ph:80', 'ph', 'AI app 80', 'https://producthunt.com/p/80', 'ai'],
    ['ph:81', 'ph', 'design tool 81', 'https://producthunt.com/p/81', 'design'],
    ['ph:82', 'ph', 'productivity 82', 'https://producthunt.com/p/82', 'prod'],
    ['ph:83', 'ph', 'SaaS 83', 'https://producthunt.com/p/83', 'saas'],
    ['ph:84', 'ph', 'mobile app 84', 'https://producthunt.com/p/84', 'mobile'],
    ['ph:85', 'ph', 'AI app 85', 'https://producthunt.com/p/85', 'ai'],
    ['ph:86', 'ph', 'design tool 86', 'https://producthunt.com/p/86', 'design'],
    ['ph:87', 'ph', 'productivity 87', 'https://producthunt.com/p/87', 'prod'],
    ['ph:88', 'ph', 'SaaS 88', 'https://producthunt.com/p/88', 'saas'],
    ['ph:89', 'ph', 'mobile app 89', 'https://producthunt.com/p/89', 'mobile'],
    ['ph:90', 'ph', 'AI app 90', 'https://producthunt.com/p/90', 'ai'],
  ]
  // Twitter 推文
  const tw = [
    ['tw:1', 'tw', 'css thread 1', 'https://x.com/u/1', 'web'],
    ['tw:2', 'tw', 'code thread 2', 'https://x.com/u/2', 'dev'],
    ['tw:3', 'tw', 'hack thread 3', 'https://x.com/u/3', 'security'],
    ['tw:4', 'tw', 'GPT thread 4', 'https://x.com/u/4', 'ai'],
    ['tw:5', 'tw', 'css thread 5', 'https://x.com/u/5', 'web'],
    ['tw:6', 'tw', 'code thread 6', 'https://x.com/u/6', 'dev'],
    ['tw:7', 'tw', 'hack thread 7', 'https://x.com/u/7', 'security'],
    ['tw:8', 'tw', 'GPT thread 8', 'https://x.com/u/8', 'ai'],
    ['tw:9', 'tw', 'css thread 9', 'https://x.com/u/9', 'web'],
    ['tw:10', 'tw', 'code thread 10', 'https://x.com/u/10', 'dev'],
    ['tw:11', 'tw', 'hack thread 11', 'https://x.com/u/11', 'security'],
    ['tw:12', 'tw', 'GPT thread 12', 'https://x.com/u/12', 'ai'],
    ['tw:13', 'tw', 'css thread 13', 'https://x.com/u/13', 'web'],
    ['tw:14', 'tw', 'code thread 14', 'https://x.com/u/14', 'dev'],
    ['tw:15', 'tw', 'hack thread 15', 'https://x.com/u/15', 'security'],
    ['tw:16', 'tw', 'GPT thread 16', 'https://x.com/u/16', 'ai'],
    ['tw:17', 'tw', 'css thread 17', 'https://x.com/u/17', 'web'],
    ['tw:18', 'tw', 'code thread 18', 'https://x.com/u/18', 'dev'],
    ['tw:19', 'tw', 'hack thread 19', 'https://x.com/u/19', 'security'],
    ['tw:20', 'tw', 'GPT thread 20', 'https://x.com/u/20', 'ai'],
    ['tw:21', 'tw', 'css thread 21', 'https://x.com/u/21', 'web'],
    ['tw:22', 'tw', 'code thread 22', 'https://x.com/u/22', 'dev'],
    ['tw:23', 'tw', 'hack thread 23', 'https://x.com/u/23', 'security'],
    ['tw:24', 'tw', 'GPT thread 24', 'https://x.com/u/24', 'ai'],
    ['tw:25', 'tw', 'css thread 25', 'https://x.com/u/25', 'web'],
    ['tw:26', 'tw', 'code thread 26', 'https://x.com/u/26', 'dev'],
    ['tw:27', 'tw', 'hack thread 27', 'https://x.com/u/27', 'security'],
    ['tw:28', 'tw', 'GPT thread 28', 'https://x.com/u/28', 'ai'],
    ['tw:29', 'tw', 'css thread 29', 'https://x.com/u/29', 'web'],
    ['tw:30', 'tw', 'code thread 30', 'https://x.com/u/30', 'dev'],
    ['tw:31', 'tw', 'hack thread 31', 'https://x.com/u/31', 'security'],
    ['tw:32', 'tw', 'GPT thread 32', 'https://x.com/u/32', 'ai'],
    ['tw:33', 'tw', 'css thread 33', 'https://x.com/u/33', 'web'],
    ['tw:34', 'tw', 'code thread 34', 'https://x.com/u/34', 'dev'],
    ['tw:35', 'tw', 'hack thread 35', 'https://x.com/u/35', 'security'],
    ['tw:36', 'tw', 'GPT thread 36', 'https://x.com/u/36', 'ai'],
    ['tw:37', 'tw', 'css thread 37', 'https://x.com/u/37', 'web'],
    ['tw:38', 'tw', 'code thread 38', 'https://x.com/u/38', 'dev'],
    ['tw:39', 'tw', 'hack thread 39', 'https://x.com/u/39', 'security'],
    ['tw:40', 'tw', 'GPT thread 40', 'https://x.com/u/40', 'ai'],
    ['tw:41', 'tw', 'css thread 41', 'https://x.com/u/41', 'web'],
    ['tw:42', 'tw', 'code thread 42', 'https://x.com/u/42', 'dev'],
    ['tw:43', 'tw', 'hack thread 43', 'https://x.com/u/43', 'security'],
    ['tw:44', 'tw', 'GPT thread 44', 'https://x.com/u/44', 'ai'],
    ['tw:45', 'tw', 'css thread 45', 'https://x.com/u/45', 'web'],
    ['tw:46', 'tw', 'code thread 46', 'https://x.com/u/46', 'dev'],
    ['tw:47', 'tw', 'hack thread 47', 'https://x.com/u/47', 'security'],
    ['tw:48', 'tw', 'GPT thread 48', 'https://x.com/u/48', 'ai'],
    ['tw:49', 'tw', 'css thread 49', 'https://x.com/u/49', 'web'],
    ['tw:50', 'tw', 'code thread 50', 'https://x.com/u/50', 'dev'],
    ['tw:51', 'tw', 'hack thread 51', 'https://x.com/u/51', 'security'],
    ['tw:52', 'tw', 'GPT thread 52', 'https://x.com/u/52', 'ai'],
    ['tw:53', 'tw', 'css thread 53', 'https://x.com/u/53', 'web'],
    ['tw:54', 'tw', 'code thread 54', 'https://x.com/u/54', 'dev'],
    ['tw:55', 'tw', 'hack thread 55', 'https://x.com/u/55', 'security'],
    ['tw:56', 'tw', 'GPT thread 56', 'https://x.com/u/56', 'ai'],
    ['tw:57', 'tw', 'css thread 57', 'https://x.com/u/57', 'web'],
    ['tw:58', 'tw', 'code thread 58', 'https://x.com/u/58', 'dev'],
    ['tw:59', 'tw', 'hack thread 59', 'https://x.com/u/59', 'security'],
    ['tw:60', 'tw', 'GPT thread 60', 'https://x.com/u/60', 'ai'],
  ]

  const all = [...github, ...ph, ...tw]
  console.log(`播种 ${all.length} 条原始数据...`)
  let i = 0
  for (const [id, source, title, url, cat] of all) {
    await pool.query(
      'INSERT INTO raw_items (id, source, title, url, raw_data, is_read, fetched_at) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (id) DO NOTHING',
      [
        id,
        source,
        title,
        url,
        JSON.stringify({ category: cat, desc: title }),
        false,
        now + i * 1000,
      ],
    )
    await pool.query(
      'INSERT INTO ai_analysis (item_id, summary, details, processed_at) VALUES ($1,$2,$3,NOW()) ON CONFLICT (item_id) DO NOTHING',
      [id, '摘要：' + title, '详细分析：' + title + ' 是一类值得关注的项目。'],
    )
    i++
  }

  // 碎片主题组（模拟「大扫除」场景：同类主题被拆成多个）
  const fragTopics: Array<[string, string]> = [
    ['AI 编程助手 Skills', 'AI 编程相关'],
    ['AI 编程技能包', 'AI 编程相关'],
    ['Claude Code 技能合集', 'AI 编程相关'],
    ['AI 绘图工具', 'AI 图像生成'],
    ['Stable Diffusion 工具', 'AI 图像生成'],
    ['游戏作弊脚本', '游戏相关'],
    ['游戏外挂执行器', '游戏相关'],
    ['游戏辅助瞄准', '游戏相关'],
    ['加密货币交易工具', '加密货币'],
    ['DeFi 套利机器人', '加密货币'],
    ['React 组件库', '前端开发'],
    ['Vue 工具集', '前端开发'],
  ]
  console.log(`播种 ${fragTopics.length} 个碎片主题组...`)
  for (let idx = 0; idx < fragTopics.length; idx++) {
    const gid = `lt:${idx}`
    const t = fragTopics[idx]
    await pool.query(
      'INSERT INTO topic_groups (id, source, topic, summary, created_at) VALUES ($1,$2,$3,$4,NOW()) ON CONFLICT (id) DO NOTHING',
      [gid, 'github', t[0], t[1]],
    )
  }
  // 主题关联：AI 类 items → lt:0/1/2，游戏类 → lt:3/4，加密类 → lt:5/6
  const topicLinks: Array<[string, string[]]> = [
    ['lt:0', ['github:gh8', 'github:gh16', 'github:gh24']],
    ['lt:1', ['github:gh8', 'github:gh16']],
    ['lt:3', ['github:gh1', 'github:gh9']],
    ['lt:4', ['github:gh1', 'github:gh9']],
    ['lt:5', ['github:gh2', 'github:gh10']],
  ]
  for (const [gid, ids] of topicLinks) {
    for (const itId of ids) {
      await pool.query(
        'INSERT INTO topic_items (topic_id, item_id) VALUES ($1,$2) ON CONFLICT DO NOTHING',
        [gid, itId],
      )
    }
  }
  // 部分 item 标记已聚合（模拟队列消费过的）
  const aggregatedIds = ['github:gh8', 'github:gh1', 'github:gh2']
  for (const itId of aggregatedIds) {
    await pool.query('UPDATE raw_items SET aggregated_at = NOW() WHERE id = $1', [itId])
  }

  await pool.end()
  console.log('✅ 种子数据完成')
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
