name: Scrape Twitter
on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:
jobs:
  scrape:
    uses: ./.github/workflows/scrape.yml
    with:
      source: twitter
      source-display-name: Twitter
    secrets: inherit
