name: Scrape ProductHunt
on:
  schedule:
    - cron: '30 */6 * * *'
  workflow_dispatch:
jobs:
  scrape:
    uses: ./.github/workflows/scrape.yml
    with:
      source: producthunt
      source-display-name: ProductHunt
    secrets: inherit
