name: Scrape GitHub Trending
on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:
jobs:
  scrape:
    uses: ./.github/workflows/scrape.yml
    with:
      source: github
      source-display-name: GitHub Trending
    secrets: inherit
